# Generated by Django 4.2.5 on 2023-09-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='car', max_length=50)),
                ('modele', models.CharField(default='xxxx', max_length=50)),
                ('prix', models.FloatField(default=0.0)),
                ('description', models.CharField(default='', max_length=1000)),
                ('color', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
