# Generated by Django 4.2.5 on 2023-09-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationdevoiture', '0003_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='annee',
            field=models.IntegerField(default=0),
        ),
    ]
