# Generated by Django 4.2.5 on 2023-09-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationdevoiture', '0004_car_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='car_name',
            field=models.CharField(default='car', max_length=100),
            preserve_default=False,
        ),
    ]
