# Generated by Django 4.2.5 on 2023-09-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationdevoiture', '0006_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='card_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cvc',
            field=models.IntegerField(blank=True, default='123', max_length=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expiration_date',
            field=models.DateField(default='2023-07-10'),
        ),
    ]
