# Generated by Django 4.2.5 on 2023-09-23 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationdevoiture', '0007_customuser_card_name_customuser_cvc_and_more'),
    ]

    operations = [
    ]
